phalcon/phalcon.io

_includes/sponsors.html, _layouts/sponsors.html
Added uptrends as new sponsor.
=> New sponsor uptrends

_layouts/download-linux.html
Also adds building for Php-Psr dependency
=> Added tap formula for 4.0.0rc2 and 4.0.0rc3

_layouts/download-linux.html
just migrated the repo from my account and fixed a couple of typos
=> homebrew-tap move reference over to phalcon/homebrew-tap repo

_includes/contributors.html, _includes/design.html, _includes/head.html, _includes/join.html, _includes/sponsors.html, _layouts/index.html
=> fix w3 validation

_data/languages/en-us.json
=> update sign for w3 validation

_layouts/download-stubs.html
=> add responsive video

_layouts/download-stubs.html
=> fix iframe for w3 validation

_includes/head.html, assets/favicons/site.webmanifest
=> add webmanifest & upd favicons

_includes/header.html
issue https://github.com/phalcon/phalcon.io/issues/74
=> fix dropdown item

404.md, Gemfile
https://github.com/phalcon/phalcon.io/issues/79
=> add 404 page

404.html
https://github.com/phalcon/phalcon.io/issues/83
=> upd 404 page

404.html, _pages/en-us/404.html
https://github.com/phalcon/phalcon.io/issues/89
=> update 404 page

_includes/sponsors.html
https://github.com/phalcon/phalcon.io/issues/121
=> add support logo

_includes/sponsors.html
https://github.com/phalcon/phalcon.io/issues/124
=> update supporters logo

_data/languages/cs-cz.json, _data/languages/de-de.json, _data/languages/el-gr.json, _data/languages/en-us.json, _data/languages/es-es.json, _data/languages/fa-ir.json, _data/languages/fr-fr.json, _data/languages/hu-hu.json, _data/languages/id-id.json, _data/languages/ja-jp.json, _data/languages/ka-ge.json, _data/languages/ko-kr.json, _data/languages/lv-lv.json, _data/languages/pt-br.json, _data/languages/ro-ro.json, _data/languages/ru-ru.json, _data/languages/tr-tr.json, _data/languages/uk-ua.json, _data/languages/zh-cn.json
resolve https://github.com/phalcon/phalcon.io/issues/144
=> update data folder links

_layouts/download-tools.html, _layouts/hosting.html, _layouts/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/147
=> update layouts folder links

_includes/header.html
resolve https://github.com/phalcon/phalcon.io/issues/157
=> Accessibility update toggle btn

_includes/design.html
resolve https://github.com/phalcon/phalcon.io/issues/161
=> reformat design.html

_includes/features_basic.html
resolve https://github.com/phalcon/phalcon.io/issues/163
=> reformat features_basic.html

_includes/features_data.html
resolve https://github.com/phalcon/phalcon.io/issues/165
=> reformat features_data.html

_includes/features_menu.html
resolve https://github.com/phalcon/phalcon.io/issues/167
=> reformat features_menu.html

_includes/features_mobile.html
resolve https://github.com/phalcon/phalcon.io/issues/169
=> reformat features_mobile.html

_includes/features_more.html
resolve https://github.com/phalcon/phalcon.io/issues/171
=> reformat features_more.html

_includes/features_views.html
resolve https://github.com/phalcon/phalcon.io/issues/173
=> reformat features_views.html

_includes/footer-js.html
resolve https://github.com/phalcon/phalcon.io/issues/175
=> reformat footer-js.html

_includes/head.html
resolve https://github.com/phalcon/phalcon.io/issues/177
=> reformat head.html

_includes/header.html
resolve https://github.com/phalcon/phalcon.io/issues/179
=> reformat headed.html

_includes/join.html
resolve https://github.com/phalcon/phalcon.io/issues/181
=> reformat join.html

_includes/menu-download.html
resolve https://github.com/phalcon/phalcon.io/issues/183
=> reformat menu-download

_includes/menu-language.html
resolve https://github.com/phalcon/phalcon.io/issues/185
=> reformat menu-language

_includes/menu-team.html
=> reformat menu-team.html

_includes/sponsors.html
resolve https://github.com/phalcon/phalcon.io/issues/189
=> reformat sponsors.html

_layouts/about.html
resolve https://github.com/phalcon/phalcon.io/issues/191
=> reformat about.html

_layouts/consulting.html
resolve https://github.com/phalcon/phalcon.io/issues/193
=> reformat consulting.html

_layouts/download-linux.html
resolve https://github.com/phalcon/phalcon.io/issues/195
=> reformat download-linux.html

_layouts/download-stubs.html
resolve https://github.com/phalcon/phalcon.io/issues/197
=> reformat download-stubs.html

_layouts/download-tools.html
resolve https://github.com/phalcon/phalcon.io/issues/199
=> reformat download-tools.html

_layouts/download-windows.html
resolve https://github.com/phalcon/phalcon.io/issues/201
=> reformat download-windows.html

_layouts/hosting.html
resolve https://github.com/phalcon/phalcon.io/issues/203
=> reformat hosting.html

_layouts/index.html
resolve https://github.com/phalcon/phalcon.io/issues/205
=> reformat index.html

_layouts/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/207
=> reformat testimonials.html

404.html
rsolvoe https://github.com/phalcon/phalcon.io/issues/209
=> reformat 404.html

_includes/sponsors.html
resolve https://github.com/phalcon/phalcon.io/issues/212
=> fix supporters block

_includes/jumbo.html, _redirects
resolve https://github.com/phalcon/phalcon.io/issues/222
=> update docs links

_includes/header.html, _layouts/support.html
resolve https://github.com/phalcon/phalcon.io/issues/224
=> correct docs links

_includes/header.html, assets/js/search.js
resolve https://github.com/phalcon/phalcon.io/issues/226
=> remove search bar

_pages/bg-bg/about.html, _pages/bg-bg/consulting.html, _pages/bg-bg/download-llinux.html, _pages/bg-bg/download-stubs.html, _pages/bg-bg/download-tools.html, _pages/bg-bg/download-windows.html, _pages/bg-bg/hosting.html, _pages/bg-bg/index.html, _pages/bg-bg/sponsors.html, _pages/bg-bg/support.html, _pages/bg-bg/team.html, _pages/bg-bg/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/251
=> remove unnecessary pages bg

_pages/da-dk/about.html, _pages/da-dk/consulting.html, _pages/da-dk/download-llinux.html, _pages/da-dk/download-stubs.html, _pages/da-dk/download-tools.html, _pages/da-dk/download-windows.html, _pages/da-dk/hosting.html, _pages/da-dk/index.html, _pages/da-dk/sponsors.html, _pages/da-dk/support.html, _pages/da-dk/team.html, _pages/da-dk/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/255
=> remove unnecessary pages dk

_pages/hy-am/about.html, _pages/hy-am/consulting.html, _pages/hy-am/download-llinux.html, _pages/hy-am/download-stubs.html, _pages/hy-am/download-tools.html, _pages/hy-am/download-windows.html, _pages/hy-am/hosting.html, _pages/hy-am/index.html, _pages/hy-am/sponsors.html, _pages/hy-am/support.html, _pages/hy-am/team.html, _pages/hy-am/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/257
=> remove unnecessary pages am

_pages/it-it/about.html, _pages/it-it/consulting.html, _pages/it-it/download-llinux.html, _pages/it-it/download-stubs.html, _pages/it-it/download-tools.html, _pages/it-it/download-windows.html, _pages/it-it/hosting.html, _pages/it-it/index.html, _pages/it-it/sponsors.html, _pages/it-it/support.html, _pages/it-it/team.html, _pages/it-it/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/259
=> remove unnecessary pages it

_pages/kk-kz/about.html, _pages/kk-kz/consulting.html, _pages/kk-kz/download-llinux.html, _pages/kk-kz/download-stubs.html, _pages/kk-kz/download-tools.html, _pages/kk-kz/download-windows.html, _pages/kk-kz/hosting.html, _pages/kk-kz/index.html, _pages/kk-kz/sponsors.html, _pages/kk-kz/support.html, _pages/kk-kz/team.html, _pages/kk-kz/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/261
=> remove unnecessary pages kz

_pages/km-kh/about.html, _pages/km-kh/consulting.html, _pages/km-kh/download-llinux.html, _pages/km-kh/download-stubs.html, _pages/km-kh/download-tools.html, _pages/km-kh/download-windows.html, _pages/km-kh/hosting.html, _pages/km-kh/index.html, _pages/km-kh/sponsors.html, _pages/km-kh/support.html, _pages/km-kh/team.html, _pages/km-kh/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/263
=> remove unnecessary pages kh

_pages/mn-mn/about.html, _pages/mn-mn/consulting.html, _pages/mn-mn/download-llinux.html, _pages/mn-mn/download-stubs.html, _pages/mn-mn/download-tools.html, _pages/mn-mn/download-windows.html, _pages/mn-mn/hosting.html, _pages/mn-mn/index.html, _pages/mn-mn/sponsors.html, _pages/mn-mn/support.html, _pages/mn-mn/team.html, _pages/mn-mn/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/267
=> remove unnecessary pages mn

_pages/nl-nl/about.html, _pages/nl-nl/consulting.html, _pages/nl-nl/download-llinux.html, _pages/nl-nl/download-stubs.html, _pages/nl-nl/download-tools.html, _pages/nl-nl/download-windows.html, _pages/nl-nl/hosting.html, _pages/nl-nl/index.html, _pages/nl-nl/sponsors.html, _pages/nl-nl/support.html, _pages/nl-nl/team.html, _pages/nl-nl/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/269
=> remove unnecessary pages nl

_pages/no-no/about.html, _pages/no-no/consulting.html, _pages/no-no/download-llinux.html, _pages/no-no/download-stubs.html, _pages/no-no/download-tools.html, _pages/no-no/download-windows.html, _pages/no-no/hosting.html, _pages/no-no/index.html, _pages/no-no/sponsors.html, _pages/no-no/support.html, _pages/no-no/team.html, _pages/no-no/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/271
=> remove unnecessary pages no

_pages/pl-pl/about.html, _pages/pl-pl/consulting.html, _pages/pl-pl/download-llinux.html, _pages/pl-pl/download-stubs.html, _pages/pl-pl/download-tools.html, _pages/pl-pl/download-windows.html, _pages/pl-pl/hosting.html, _pages/pl-pl/index.html, _pages/pl-pl/sponsors.html, _pages/pl-pl/support.html, _pages/pl-pl/team.html, _pages/pl-pl/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/273
=> remove unnecessary pages pl

_pages/pt-pt/about.html, _pages/pt-pt/consulting.html, _pages/pt-pt/download-llinux.html, _pages/pt-pt/download-stubs.html, _pages/pt-pt/download-tools.html, _pages/pt-pt/download-windows.html, _pages/pt-pt/hosting.html, _pages/pt-pt/index.html, _pages/pt-pt/sponsors.html, _pages/pt-pt/support.html, _pages/pt-pt/team.html, _pages/pt-pt/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/275
=> remove unnecessary pages pt

_pages/sk-sk/about.html, _pages/sk-sk/consulting.html, _pages/sk-sk/download-llinux.html, _pages/sk-sk/download-stubs.html, _pages/sk-sk/download-tools.html, _pages/sk-sk/download-windows.html, _pages/sk-sk/hosting.html, _pages/sk-sk/index.html, _pages/sk-sk/sponsors.html, _pages/sk-sk/support.html, _pages/sk-sk/team.html, _pages/sk-sk/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/277
=> remove unnecessary pages sk

_pages/sv-se/about.html, _pages/sv-se/consulting.html, _pages/sv-se/download-llinux.html, _pages/sv-se/download-stubs.html, _pages/sv-se/download-tools.html, _pages/sv-se/download-windows.html, _pages/sv-se/hosting.html, _pages/sv-se/index.html, _pages/sv-se/sponsors.html, _pages/sv-se/support.html, _pages/sv-se/team.html, _pages/sv-se/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/279
=> remove unnecessary pages se

_pages/th-th/about.html, _pages/th-th/consulting.html, _pages/th-th/download-llinux.html, _pages/th-th/download-stubs.html, _pages/th-th/download-tools.html, _pages/th-th/download-windows.html, _pages/th-th/hosting.html, _pages/th-th/index.html, _pages/th-th/sponsors.html, _pages/th-th/support.html, _pages/th-th/team.html, _pages/th-th/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/281
=> remove unnecessary pages th

_pages/tl-ph/about.html, _pages/tl-ph/consulting.html, _pages/tl-ph/download-llinux.html, _pages/tl-ph/download-stubs.html, _pages/tl-ph/download-tools.html, _pages/tl-ph/download-windows.html, _pages/tl-ph/hosting.html, _pages/tl-ph/index.html, _pages/tl-ph/sponsors.html, _pages/tl-ph/support.html, _pages/tl-ph/team.html, _pages/tl-ph/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/283
=> remove unnecessary pages ph

_pages/vi-vn/about.html, _pages/vi-vn/consulting.html, _pages/vi-vn/download-llinux.html, _pages/vi-vn/download-stubs.html, _pages/vi-vn/download-tools.html, _pages/vi-vn/download-windows.html, _pages/vi-vn/hosting.html, _pages/vi-vn/index.html, _pages/vi-vn/sponsors.html, _pages/vi-vn/support.html, _pages/vi-vn/team.html, _pages/vi-vn/testimonials.html
resolve https://github.com/phalcon/phalcon.io/issues/285
=> remove unnecessary pages vn

assets/js/search.js
resolve https://github.com/phalcon/phalcon.io/issues/288
=> remove search js

_includes/footer-js.html, _includes/head.html, _includes/header.html, assets/css/custom.css, assets/css/dark.css, assets/js/core.js
resolve https://github.com/phalcon/phalcon.io/issues/291
=> add dark theme

_includes/footer-js.html, _layouts/index.html, assets/css/dark.css, assets/js/core.js
resolve https://github.com/phalcon/phalcon.io/issues/293
=> fix dark theme

_includes/footer-js.html, _includes/head.html
resolve https://github.com/phalcon/phalcon.io/issues/298
=> add caching to css js files

Gemfile, _includes/head.html, assets/css/dark.css
resolve https://github.com/phalcon/phalcon.io/issues/305
=> update theme js

_includes/footer-js.html, _includes/head.html, _includes/header.html, assets/css/dark.css, assets/js/theme.js
resolve https://github.com/phalcon/phalcon.io/issues/310
=> add theme switch btn

_includes/footer-js.html, _includes/head.html
resolve https://github.com/phalcon/phalcon.io/issues/312
=> update css & js

404.html
resolve https://github.com/phalcon/phalcon.io/issues/320
=> fix 404 page

assets/fix.css
resolve https://github.com/phalcon/phalcon.io/issues/330
=> add hover to btn

assets/fix.css
resolve https://github.com/phalcon/phalcon.io/issues/334
=> add hover to btns

assets/fix.css
resolve https://github.com/phalcon/phalcon.io/issues/338
=> update contribute btn color dark theme

_redirects
resolve https://github.com/phalcon/phalcon.io/issues/342
=> upd redirects

Gemfile
resolve https://github.com/phalcon/phalcon.io/issues/344
=> bump jekyll
